/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fontChoose.java
 *
 * Created on Oct 27, 2010, 5:14:53 PM
 */



import java.awt.Font;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Pham Duy Anh
 */
public class fontChoose extends javax.swing.JDialog {

    public fontChoose(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListFont = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListFontStyle = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListSize = new javax.swing.JList();
        txtFont = new javax.swing.JTextField();
        txtFontStyle = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        bntOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtPreview = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("fontChoose");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ListFont.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListFont.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListFontValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListFont);

        ListFontStyle.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListFontStyle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListFontStyleValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListFontStyle);

        ListSize.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListSize.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListSizeValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(ListSize);

        txtFont.setEditable(false);
        txtFont.setText("jTextField1");

        txtFontStyle.setEditable(false);
        txtFontStyle.setText("jTextField2");

        txtSize.setEditable(false);
        txtSize.setText("jTextField3");

        bntOK.setText("OK");
        bntOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtPreview.setEditable(false);
        txtPreview.setText("Text Sample");
        txtPreview.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Font");

        jLabel2.setText("Font Style");

        jLabel3.setText("Size");

        jLabel4.setText("Preview");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFont)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFontStyle, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSize, 0, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bntOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4)
                    .addComponent(txtPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntOK)
                    .addComponent(txtFontStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String []fontName=ge.getAvailableFontFamilyNames();
        ListFont.setListData(fontName);
        String []fontStyle={"Regular","Italic","Bold","Bold Italic"};
        ListFontStyle.setListData(fontStyle);
        String []fontSize ={"10","12","14","16","18","20","22","24"};
        ListSize.setListData(fontSize);
        ListFont.setSelectedIndex(0);
        txtFont.setText(ListFont.getSelectedValue().toString());
        ListFontStyle.setSelectedIndex(0);
        txtFontStyle.setText(ListFontStyle.getSelectedValue().toString());
        ListSize.setSelectedIndex(0);
        txtSize.setText(ListSize.getSelectedValue().toString());
        txtPreview.setFont(new Font("Arial",Font.PLAIN,12));
        
    }//GEN-LAST:event_formWindowOpened
    int Fontstyle=Font.PLAIN;
    String Fontname = ".Vn3DH";
    int Fontsize = 8;
    public boolean isOK=false;
    private void ListFontValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListFontValueChanged
        txtFont.setText(ListFont.getSelectedValue().toString());
        Fontname = ListFont.getSelectedValue().toString();
        txtPreview.setFont(new Font(Fontname,Fontstyle,Fontsize));
    }//GEN-LAST:event_ListFontValueChanged

    private void ListFontStyleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListFontStyleValueChanged
        // TODO add your handling code here:
        txtFontStyle.setText(ListFontStyle.getSelectedValue().toString());
        if(txtFontStyle.getText().equals("Regular"))
            Fontstyle = Font.PLAIN;
        else if(txtFontStyle.getText().equals("Italic"))
            Fontstyle = Font.ITALIC;
        else if (txtFontStyle.getText().equals("Bold"))
            Fontstyle = Font.BOLD;
        else
                Fontstyle = Font.BOLD + Font.ITALIC;
        txtPreview.setFont(new Font(Fontname,Fontstyle,Fontsize));
    }//GEN-LAST:event_ListFontStyleValueChanged

    private void ListSizeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListSizeValueChanged
        // TODO add your handling code here:
        txtSize.setText(ListSize.getSelectedValue().toString());
        Fontsize = (int)Double.parseDouble(txtSize.getText());
        txtPreview.setFont(new Font(Fontname,Fontstyle,Fontsize));
    }//GEN-LAST:event_ListSizeValueChanged
    private void bntOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOKActionPerformed
        // TODO add your handling code here:
       isOK=true;
       txtPreview.setFont(txtPreview.getFont());
       this.dispose();
    }//GEN-LAST:event_bntOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fontChoose dialog = new fontChoose(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListFont;
    private javax.swing.JList ListFontStyle;
    private javax.swing.JList ListSize;
    private javax.swing.JButton bntOK;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtFont;
    private javax.swing.JTextField txtFontStyle;
    public static javax.swing.JTextField txtPreview;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables

}
